# Generated by Django 3.0.1 on 2020-01-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='title',
        ),
    ]
